apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmapss-output-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ml-output   # Path inside Minikube VM or Kind node
