name : CI Pipeline (Docker)

on :
  push : 
    branches : 
      - feature_ci_cd_github_actions
  pull_request :
    branches : 
      - feature_ci_cd_github_actions

jobs :
  Docker:
    runs-on : ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name : Set up python
      uses : actions/setup-python@v4
      with:
        python-version : '3.9'

    - name : Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name : Test Holder
      run : echo "No tests yet"

    - name : Install Kind
      run : |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        
    - name : Install kubectl
      shell: bash -l {0}
      run: |
        KUBE_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -Lo kubectl "https://dl.k8s.io/release/${KUBE_VERSION}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name : create Kind cluster
      run : kind create cluster --name nasa-anomaly-cluster
      #run : |
      #  if ! kind get clusters | grep -q "nasa-anomaly"; then
      #  kind create cluster --name nasa-anomaly
      #  else
      #  echo "Cluster nasa-anomaly already exists. Skipping creation."
      #  fi   # For local testing using 'act'
    

    - name : Build Docker image
      run: docker build -t nasa-anomaly:latest .

    - name : Load Docker image into Kind
      run : kind load docker-image nasa-anomaly:latest --name nasa-anomaly

    - name : Deploy Flask app
      run : |
        kubectl apply -f k8s/manifests/deployment.yaml
        kubectl rollout status deployment/cmapss-isolationforest
        kubectl get pods
        kubectl get svc

    - name : Smoke test via ClusterIP + curl pod 
      run : |
        # Run a temporary curl pod to test service
        kubectl run curl-test --rm -i --restart= Never \
        --image=curlimages/curl \
        -- curl -s http://CmapssClusterIP-service :8000/ || exit 1
